### ISSUE TITLE
ErrorException in ResponseFormatter.php line 284 (Undefined index: metadata)

### ISSUE THREAD

**Issue by frednotet** [graphaware/neo4j-php-client#10]
If $elts is an array but the values within this are NULL; we don't have the key "metadata" and so we have an exception...

@line 282; if I verify the existence of "$elts['metadata']"; I don't have this exception anymore...

```if (is_array($elts) && isset($elts['metadata'])) ```

**Comment by frednotet** [comment]
I think both errors are related : 

FatalErrorException in Result.php line 220:
Call to a member function getId() on array

**Comment by ikwattro** [comment]
Fixed in last commit and 3.3.15 released
