### ISSUE TITLE
Cypher MERGE problem : cannot create relationship

### ISSUE THREAD

**Issue by averchinine** [graphaware/neo4j-php-client#105]
Hello,

I have a problem with my cypher queries. The MERGE doesn't seems to work. If I run this example from doc : 
`$neoClient = ClientBuilder::create()->addConnection('default', "http://".\Yii::$app->params['neo4j_user'].":".\Yii::$app->params['neo4j_passwd']."@".\Yii::$app->params['neo4j_server'].":".\Yii::$app->params['neo4j_http_port'])->addConnection('bolt', "bolt://".\Yii::$app->params['neo4j_user'].":".\Yii::$app->params['neo4j_passwd']."@".\Yii::$app->params['neo4j_server'].":".\Yii::$app->params['neo4j_bolt_port'])->build();
        $stack = $neoClient->stack();
        $stack->push('CREATE (n:Person {uuid: {uuid} })', ['uuid' => '123-fff']);
        $stack->push('MATCH (n:Person {uuid: {uuid1} }), (n2:Person {uuid: {uuid2} }) MERGE (n)-[:FOLLOWS]->(n2)', ['uuid1' => '123-fff', 'uuid2' => '456-ddd']);
        $neoClient->runStack($stack);`

I only got the Person with uuid 123-fff created. Nothing else.

PHP : 7.1.3
neo4j : 3.1.2
Java : 1.8.0_111

All is running on macOS

**Comment by ikwattro** [comment]
Does the person with uuid2 exist in your database ?

**Comment by averchinine** [comment]
Non, I only have one node.
Seems that 'MATCH (n:Person {uuid: {uuid1} }), (n2:Person {uuid: {uuid2} }) MERGE (n)-[:FOLLOWS]->(n2)' was not executed.

**Comment by ikwattro** [comment]
it was excecuted, but as it cannot match the person2 it will not go further

**Comment by averchinine** [comment]
But this query create the person2 and relation when I write it directly in neo4j web browser.

**Comment by ikwattro** [comment]
```
$stack->push('CREATE (n:Person {uuid: {uuid} })', ['uuid' => '123-fff']); 
$stack->push('MATCH (n:Person {uuid: {uuid1} }), (n2:Person {uuid: {uuid2} }) 
MERGE (n)-[:FOLLOWS]->(n2)', ['uuid1' => '123-fff', 'uuid2' => '456-ddd']);
```

No it doesn't create the person2, it MATCH and as there is no MATCH, it will find nothing and the query will stop, if you want to create it you can change your query like this : 

```
$stack->push('CREATE (n:Person {uuid: {uuid} })', ['uuid' => '123-fff']); 
$stack->push('MATCH (n:Person {uuid: {uuid1} }) MERGE (n2:Person {uuid: {uuid2} }) MERGE (n)-[:FOLLOWS]->(n2)');
```

**Comment by averchinine** [comment]
Ok, I apologies, I have a problem with another query and try to debug following example in the doc and as it was not working I guess it was the same problem. Doc example is running with existing Person2.

This query is working in the neo4j browser view (Région are existing nodes) :
"MATCH (r:Région) WHERE r.code={code_r} CREATE (:Département {code:{code_d}, nom:{nom}, nom_maj:{nom_maj}, centre:{centre}, location:{loc}})-[:région]->(r)"

But I nothing was created (neither Département nor relation) when I try to run this on my php app.

**Comment by averchinine** [comment]
If I change query to this : 

```
$stack->push("CREATE (:Département {code:{code_d}, nom:{nom}, nom_maj:{nom_maj}, centre:{centre}, location:{loc}})", ['code_d' => $k, 'nom_maj' => $v['uppercase'], 'nom' => $v['normal'], 'centre' => $v['centre'], 'loc' => $v['coordinates']]);
              $stack->push('MATCH (r:Région {code: {code_r}}), (d:Département {code: {code_d}}) MERGE (r)-[:région]->(d)', ['code_d' => $k, 'code_r' => $v['region']]);
```

Nodes "Département" are created but no relationship.

**Comment by ikwattro** [comment]
I really would suggest you check the value of your variables and what is in the graph or not. I added an example in a test here : https://github.com/graphaware/neo4j-php-client/blob/issue-105/tests/Issues/Issue105Test.php

**Comment by averchinine** [comment]
I ran you test, this was working.

I have already check variable value (making str_replace on each {var} and echo result). 
When I paste result in neo4j browser, it works.
`MATCH (r:Region {code: 32}) CREATE (:Departement {code:02, nom:"Aisne", nom_maj:"AISNE", centre:"[2.994105543526175,49.21712786254923]", location:"[[49.21067457863414,2.990225735893543],[49.21093630547229,2.99173787141916],[49.2124675133333,2.995129851815306],[49.213982423149425,2.997447522992715],[49.218836179125475,3.002755835908097],[49.21969114041634,3.002560993428946],[49.22221737537854,3.000605280421168],[49.22321526773688,2.998903336989629],[49.223534404147784,2.99808391613353],[49.22358114646433,2.997742148417547],[49.22252912836642,2.992995998614239],[49.2205726211804,2.98932214978673],[49.21874467624184,2.986692959254964],[49.21567264372285,2.985694682871959],[49.213081659945594,2.985455251144253],[49.21294593331782,2.985659757832629],[49.21153744190427,2.98809174802874],[49.21072219240528,2.989814062999361],[49.21067457863414,2.990225735893543]]"})-[:region]->(r)`

By the way, thanks a lot for your help, I will investigate further alone.

**Comment by ChristianVermeulen** [comment]
@averchinine @ikwattro Have you ever found out what the problem is? I'm having the same issue...

```
        $stack = $this->client->stack();
        $createQuery = 'CREATE (n:Province) set n += {infos}';
        $relationQuery = 'MATCH (p:Province) MATCH (c:Country) WHERE p.code = {code} AND c.code = "NL" CREATE (p)-[:IN]->(c)';

        $stack->push($createQuery, [
            'infos' => [
                'id'   => $id,
                'name' => $name,
                'code' => $code
            ]
        ]);

        $stack->push($relationQuery, ['code'=>$code]);

        $this->client->runStack($stack);
```

I know for sure the `Country`-node exists. After running this (12 times for 12 provinces) all provinces are created, but no relations are created. If I run the query manually like you did in the browser it does work... The fact that the province gets created tells us the parameters are correct as well.

For the second query I also tried `MERGE` and `MATCH (p:Province {code: {code}})` (instead of the WHERE clause).

What is going on here?

**Comment by ChristianVermeulen** [comment]
Hmm... I've just built this query in the browser:
```
MATCH (c:Country {code:"NL"}) MERGE (p:Province {id: {id}, code: {code}, name:{name}})-[:IN_COUNTRY]->(c)
```

So both my creation AND relation are in one query. Still I end up with only nodes, but no relations.

![cpskai4c6wlha](https://user-images.githubusercontent.com/1062751/28217896-16c7dec6-68b7-11e7-815c-3a9263922338.gif)

**Comment by ikwattro** [comment]
@ChristianVermeulen I already found the problem and it appeared to be human.

I created a test again here with the exact same query as you : 

https://github.com/graphaware/neo4j-php-client/blob/16e72f3b8a049f923add1aa809c531d5571548c4/tests/Issues/Issue105Test.php#L48

Can you debug the value of the $code variable ?

**Comment by ikwattro** [comment]
@ChristianVermeulen I would happy to help further if you can provide a reproducable test or send me a copy of your db privately if you want.

**Comment by ChristianVermeulen** [comment]
@ikwattro Well, after that last single query I have these nodes in the db (12 total):
```
{
  "code": "GR",
  "name": "Groningen",
  "id": "1a42d4c8-e7ea-52a3-89ec-cb9cbc3f0290"
}
--
{
  "code": "FR",
  "name": "Friesland",
  "id": "206d6e4d-391c-56fa-ad6c-15e6ab5b9aa5"
}
{
  "code": "DR",
  "name": "Drenthe",
  "id": "77f00048-87d1-5a3b-8854-c8ba82cbd074"
}
{
  "code": "OV",
  "name": "Overijssel",
  "id": "eda77997-cc45-5311-b4c4-d8008074d5f8"
}
```

That pretty much confirms the variable values are correct right?

**Comment by ChristianVermeulen** [comment]
I think you are still missing assertions in that test, no? Did it really work for you? Caus then I am really at a loss of where the problem might be 😂

**Comment by ikwattro** [comment]
I don't need assertions, it was just for simulating your query. I ran the test and could see there is no issues in the db.

If you need assertions, you can extend the test and add some to prove the issue.

**Comment by averchinine** [comment]
Hello all,

I don't know if this can help but my problem was a type problem. When I create first node, one attribute is created as integer. When I launch merge query to add second node and link with first one, first node search is done with a string type on the integer attribute. So this doesn't match. No node find to set relation.

**Comment by ChristianVermeulen** [comment]
@averchinine hmm, in my case they are all the same so that should not be a problem.... The weird thing is also that running it in the browser interface works like a charm, but that exact same query from my php client doesn't.

This one to be exact->
```
MATCH (c:Country {code:"NL"}) MERGE (p:Province {id: {id}, code: {code}, name:{name}})-[:IN_COUNTRY]->(c)
```

**Comment by ChristianVermeulen** [comment]
So, I've just managed to get it to work. I can't tell you why, but here are my changes:

For adding the Country I changed:
```php
        $query = 'CREATE (n:Country) set n += {infos}';
        
       $this->client->run(
            $query,
            [
                'infos' => [
                    'id'   => $id,
                    'name' => $name,
                    'code' => $code
                ]
            ]
        );
```
Into ->
```php
        $query = 'CREATE (n:Country {id: {id}, code: {code}, name:{name}})';

        $this->client->run(
            $query,
            [
                'id'   => $id,
                'name' => $name,
                'code' => $code
            ]
        );
```

And for the relation I changed:
```
MATCH (c:Country {code:"NL"}) MERGE (p:Province {id: {id}, code: {code}, name:{name}})-[:IN_COUNTRY]->(c)
```
Into ->
```
MATCH (c:Country {code:"NL"}) MERGE (p:Province {id: {id}, code: {code}, name:{name}})-[r:IN_COUNTRY]->(c) RETURN r
```

My theory is that the most important change here is the fact that I am returning the relation in the last query. If the change in the first query had any effect, I wouldn't know how....

![](https://d.justpo.st/media/images/2013/03/463e4e4f4acb9afc185a067b7f360321.jpg)

**Comment by sfdreverman** [comment]
Hi Christian,

What I see is that you are trying to create (if not exists) both the node (the province) and the relationship (in_country) in the same statement.
A more neat way to create the province is to first create it. In a next MERGE statement, the country and province can be linked:

MATCH (c:Country {code:"NL"}) 
MERGE (p:Province {id: {id}, code: {code}, name:{name}})
MERGE (p)-[r:IN_COUNTRY]->(c)

The difference is that your MERGE statement will try to match the ENTIRE pattern, including the (non)existence of the (p) node.
In my example the first MERGE statement will only try to match the (p) node, if not found create it. (now we know the (p) and (c) node exist) The second MERGE will only focus on merging the relation pattern. This is a much safer way of ensuring the correctness of creation and order of your queries.

**Comment by ChristianVermeulen** [comment]
Thanks for the tip @sfdreverman! I've updated my code for it.
