### ISSUE TITLE
Add PHP variable in the query cypher

### ISSUE THREAD

**Issue by KevinEstia98** [graphaware/neo4j-php-client#111]
Hello everyone,

I create this issue because I would like to know how insert in the cypher query a php variable. I have tried different writting, but without success.  

<?php 
require_once 'composer/vendor/autoload.php';
use GraphAware\Neo4j\Client\ClientBuilder;

$client = ClientBuilder::create()
              ->addConnection('default','http://neo4j@localhost:7474')
               ->build();

$name="Kevin";
$params= ['name' => $name];
$query = 'MATCH (n:User) WHERE n.name ={name] RETURN DISTINCT n';
$result = $client->run($query);

                          //I HAVE TRIED THIS WRITTING
//$name="Kevin";
//$query = 'MATCH (n:User) WHERE n.name ='.$name.' RETURN DISTINCT n';
//$result = $client->run($query);

foreach ($result->getRecords() as $record){
                 echo "\r\n";
                 echo sprintf('Person name is: %s', $record->get("n")->value('name'));
}
?>

I think my query is not good, but I don't other ideas. 
Thank you for your help.

**Comment by ikwattro** [comment]
```
$query = 'MATCH (n:User) WHERE n.name ={name] RETURN DISTINCT n
```

Your closing tag for `name` is wrong. Should be `}` instead of `]`.

```
$query = 'MATCH (n:User) WHERE n.name ={name} RETURN DISTINCT n
```

Also no need for distinct here

```
$query = 'MATCH (n:User) WHERE n.name ={name} RETURN n
```

Please use StackOverflow for such questions and keep this channel for issues and feature requests.

Thanks

**Comment by KevinEstia98** [comment]
Thank you for your answer, 
but sadly this query don't work, and yet I have follow your remark.
I am sorry to had used this channel for my question for the futur I will use StackOverflow.

**Comment by ikwattro** [comment]
@KevinEstia98 `don't work` means nothing.  What is not working ?

**Comment by KevinEstia98** [comment]
It is possible to speak french together? because I saw on your profil you are fluent in French.

**Comment by KevinEstia98** [comment]
@ikwattro It is possible to speak french together? because I saw on your profil you are fluent in French.

**Comment by ikwattro** [comment]
Evidemment !

**Comment by KevinEstia98** [comment]
Super merci, tout d'abord je vous remercie de m'accorder votre temps pour m'aider à résoudre mon problème. Comme je l'ai expliqué dans ma question j'essaye de faire une requête Neo4j en utilisant une variable PHP. En essayant votre réponse ce matin, malheureusement la requête n'a pas aboutit.

**Comment by ikwattro** [comment]
Ok mais qu'est-ce qui n'a pas abouti. Le mieux serait de montrer le code final ainsi que le résultat de la même requête dans le browser neo4j.

**Comment by KevinEstia98** [comment]
Je vous ai écrit le code pour l'instant sur lequel j'essaye de faire fonctionner la requête. 

<?php 

require_once 'composer/vendor/autoload.php';
use GraphAware\Neo4j\Client\ClientBuilder;

$client = ClientBuilder::create() -> addConnection('default','http://neo4j@localhost:7474') ->build(); 

$name="Kevin"; 
$params= ['name' => $name];
 $query = 'MATCH (n:User) WHERE n.name ={name} RETURN n';
 $result = $client->run($query); 

foreach ($result->getRecords() as $record){
                  echo sprintf('Person name is: %s', $record->get("n")->value('name')); } 

?> 

Je vous joint également la capture d'écran faite sur le browser neo4j avec la requête que je cherche à faire. Je vous remercie.


![capture](https://user-images.githubusercontent.com/19806423/27425517-f8d4051e-5738-11e7-8552-8e9d241d3dbc.PNG)

**Comment by KevinEstia98** [comment]
Voici le code sur lequel je suis actuellement en train de travailler, et sur lequel j'essaye d'effectuer la requête. 

```
<?php

require_once  'composer/vendor/autoload.php';
use GraphAware\Neo4j\Client\ClientBuilder;

$client = ClientBuilder::create()->addConnection('default','http://neo4j@localhost:7474') ->build(); 

$name="Kevin";
 $params= ['name' => $name];
 $query = 'MATCH (n:User) WHERE n.name ={name} RETURN n';
 $result = $client->run($query); 

foreach ($result->getRecords() as $record){ 
                  echo sprintf('Person name is: %s', $record->get("n")->value('name')); 
}
 ?>

```

**Comment by KevinEstia98** [comment]
Je vous joins également une capture d'écran du browser neo4j avec la même requête.

![capture](https://user-images.githubusercontent.com/19806423/27425990-7b584e90-573a-11e7-807d-23553dc5421b.PNG)

En vous remerciant de votre aide.

**Comment by ikwattro** [comment]
Ok je vois, tu ne passes pas les paramètres avec la requête ;-)

```php
$name= "Kevin";
 $params = ['name' => $name];
 $query = 'MATCH (n:User) WHERE n.name = {name} RETURN n';
 $result = $client->run($query, $params); // <- passer les paramètres 

foreach ($result->getRecords() as $record){ 
                  echo sprintf('Person name is: %s', $record->get("n")->value('name')); 
}
 ?>
```

**Comment by KevinEstia98** [comment]
Super merci beaucoup. Vous me sauvez, car je suis actuellement en stage, et je dois développer une petite IHM en PHP avec une connexion à la base Neo4j avec plus tard de petite fonctionnalité telle que la possibilité de télécharger une fichier CSV à partir du résultat de la requête, etc.. . En tout cas, je vous remercie de votre aide, d'avoir pris le temps. A l'avenir je poserai mes questions sur Stackoverflow.
