### ISSUE TITLE
How can I increase transaction session time ?

### ISSUE THREAD

**Issue by iit2011081** [graphaware/neo4j-php-client#116]
After adding 3-4 queries to a transaction it says This Transaction is closed, giving error on line no. vendor/graphaware/neo4j-php-client/src/HttpDriver/Transaction.php:222. It didn't happen with neoxygen library. Is there any way to increase the default session time ?
```
$transaction = $this->client->transaction();
$transaction->push($query, $params);
$transaction->push($query, $params);
$transaction->commit();
```

**Comment by ikwattro** [comment]
Are you using bolt or http ?

**Comment by iit2011081** [comment]
http

**Comment by ikwattro** [comment]
Then it is written in the README https://github.com/graphaware/neo4j-php-client#http-client-settings

**Comment by iit2011081** [comment]
this one CURLOPT_CONNECTTIMEOUT ?

**Comment by ikwattro** [comment]
yes

**Comment by iit2011081** [comment]
Still getting same error , 
I am creating connection like this 
```
$neo4j_string = "http://".$data['neo4j_authUser'].":".$data['neo4j_authPassword']."@".$data['neo4j_host'].":".$data['neo4j_port'];
$this->client = ClientBuilder::create([ClientBuilder::TIMEOUT_CONFIG_KEY => 20])->addConnection('default',$neo4j_string )->build();
$transaction = $this->client->transaction();
```
Is this connect ? I don't know what's is happening, My api is returning response in less than 1 sec, why transaction close error ? And it is happening only with transaction queries.

**Comment by ikwattro** [comment]
```
ClientBuilder::create([ClientBuilder::TIMEOUT_CONFIG_KEY => 20])
```

Are you sure about this?

**Comment by iit2011081** [comment]
I don't know how to increase the session time, so I done this way ? Do you have any other way to increase timeout ?

**Comment by ikwattro** [comment]
Maybe read carefully what is written in the README. Again here https://github.com/graphaware/neo4j-php-client#http-client-settings

**Comment by iit2011081** [comment]
I read it. but where to enter this CURLOPT_CONNECTTIMEOUT, I don't want to edit in library.

**Comment by ikwattro** [comment]
Are you seriously serious ???????

```php
$options = [
    CURLOPT_CONNECTTIMEOUT => 3, // The number of seconds to wait while trying to connect.
    CURLOPT_SSL_VERIFYPEER => false // Stop cURL from verifying the peer's certificate
];
$httpClient = new Client(null, null, $options);

$config = \GraphAware\Neo4j\Client\HttpDriver\Configuration::create($httpClient);
$client = ClientBuilder::create()
    ->addConnection('default', 'http://neo4j:password@localhost:7474', $config)
    ->build();
```

What is not understandable ?

**Comment by iit2011081** [comment]
One last thing, where to find this Client library used in $httpClient = new Client(null, null, $options); The one's which I have are incompatible. 
`Argument 1 passed to GraphAware\\Neo4j\\Client\\HttpDriver\\Configuration::create() must be an instance of Http\\Client\\HttpClient, instance of GuzzleHttp\\Client given`

**Comment by iit2011081** [comment]
I am able to find the client library , \Http\Client\Curl\Client. But now , nothing is working. Every query is giving exception "Unsupported Media Type".

**Comment by 0xfff** [comment]
see #112

**Comment by 0xfff** [comment]
btw this is how i am connecting:
```
use GraphAware\Neo4j\Client\ClientBuilder;
use Http\Adapter\Guzzle6\Client;

$httpClient = \Http\Adapter\Guzzle6\Client::createWithConfig(['timeout'=>$neo_timeout]);
$config = \GraphAware\Neo4j\Client\HttpDriver\Configuration::create($httpClient);
    $neo4j  = ClientBuilder::create()
            -> addConnection('default', $neo_ip, $config)
            -> build();
```
