### ISSUE TITLE
Guzzle refused the connection, using bolt

### ISSUE THREAD

**Issue by gusbemacbe** [graphaware/neo4j-php-client#120]
Hello, @ikwattro !

I used:

```
$neo4j_url1 = "http://neo4j:rains-straps-kiloliter@54.236.46.233:34566";
$neo4j_url2 = "bolt://neo4j:rains-straps-kiloliter@54.236.46.233:34566";

$client = ClientBuilder::create()
    ->addConnection('default', $neo4j_url1)
    ->addConnection('bolt', $neo4j_url2)
    ->build();
```

Because, with this bolt, the project would work without depending on the server app of Neo4j, so I want to show my project to my friends and teachers in other computers of their without neo4j. 

The error:

`Fatal error: Uncaught RuntimeException: Error creating resource: [message] fopen(http://...@54.236.46.233:34566/db/data/transaction/commit): failed to open stream: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente. [file] C:\Users\aluno6\Downloads\cities-finder\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php [line] 324 in C:\Users\aluno6\Downloads\cities-finder\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php:252 Stack trace: #0 C:\Users\aluno6\Downloads\cities-finder\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(335): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure)) #1 C:\Users\aluno6\Downloads\cities-finder\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array) #2 C:\Users\aluno6\Downloads\cities-finder\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #3 C:\U in C:\Users\aluno6\Downloads\cities-finder\vendor\php-http\guzzle6-adapter\src\Promise.php on line 135`

Is there any solution to load the page without dependencies of bolt or server?

Gustavo

**Comment by ikwattro** [comment]
You seem to use the bolt port with an http connection. Guzzle is for http only, check your neo4j ports correctly.

**Comment by ikwattro** [comment]
There is no dependency of neo4j bolt port open, you can just use http
