### ISSUE TITLE
How can I create a parallel SQL connection with this?

### ISSUE THREAD

**Issue by anshajgoel** [graphaware/neo4j-php-client#126]
If I need to use two databases, SQL and Neo4j, how do I change the config files for the same?

**Comment by ikwattro** [comment]
You cannot, Neo4j do not use SQL. And this driver has no support for SQL, you will need to use a SQL driver.

**Comment by anshajgoel** [comment]
Well, I meant to use both the databases simultaneously in Laravel. Although I got a workaround. Thanks for the reply.

**Comment by ikwattro** [comment]
I understood, this has nothing to do with neo or sql, just how to do some stuff in generic php
