### ISSUE TITLE
Result object should have a toGraphJSON() method

### ISSUE THREAD

**Issue by tigerhawkvok** [graphaware/neo4j-php-client#127]
It's a bit crazy it doesn't exist, honestly.

The use cases are obvious: for interaction with other libraries, like [Alchemy.js](https://graphalchemist.github.io/Alchemy).

**Comment by ikwattro** [comment]
What I find crazy is that the only use case you give is dead since more than 3 years.

What does d3.js is using? What does ogma.js uses? What does sigma.js uses? and the list is long.

This is a driver, writing a tiny wrapper for the js library you are using is not that too much effort!

**Comment by tigerhawkvok** [comment]
[30 seconds of Google shows that the standard is used by plenty of people](https://www.google.com/search?q=graphjson&rlz=1C1GGRV_enUS764US764&oq=graphjson&aqs=chrome..69i57j0l5.2000j0j7&sourceid=chrome&ie=UTF-8)

- [Scala](www.scala-graph.org/api/json/api/index/index-d.html)
- [Go](https://godoc.org/github.com/adrianco/spigo/tooling/graphjson)
- [Netflix uses it internally](https://netflix.github.io/falcor/documentation/jsongraph.html)
- [N4J's Ruby driver provides it](http://neo4jrb.io/neo4j-core/doc/Neo4j/Core/GraphJSON.html)
- [NNVM deep learning uses it](http://nnvm.tvmlang.org/json_spec.html)

The fact I happen to want to use it in JS doesn't mean that it's not an actual standard actually used by multiple projects. I pointed you to probably the most readily applicable use case for PHP (a JS front end), but asking the driver to make its results digestible in other contexts isn't very extreme. Sure, I can write a wrapper, but why are you asking all your users to reinvent the wheel?

**Comment by ikwattro** [comment]
> Sure, I can write a wrapper, but why are you asking all your users to reinvent the wheel?

This is the beauty of open-source, you can create, publish and maintain a wrapper that people can reuse by just adding it to their composer.json. The super cool thing would be to support even other formats like for d3 which is widely used.
