### ISSUE TITLE
how to use event dispatcher

### ISSUE THREAD

**Issue by ismaeladra1** [graphaware/neo4j-php-client#131]
please help me to use event dispatcher give me example or anything

**Comment by ikwattro** [comment]
@ismaeladra1 

Something not understandable in the README and the tests ?

https://github.com/graphaware/neo4j-php-client#event-dispatching

https://github.com/graphaware/neo4j-php-client/blob/master/tests/Integration/BuildWithEventListenersIntegrationTest.php

https://github.com/graphaware/neo4j-php-client/blob/master/tests/Integration/EventListener.php
