### ISSUE TITLE
Parameters issues

### ISSUE THREAD

**Issue by nicolaschaillan** [graphaware/neo4j-php-client#133]
Any reason why the following query is not supported?

$query = "MATCH (c:Company) WHERE ID(c)={value} RETURN c";

Using 
$db->run($query, array('value' => $value);

It seems I can't have parameters in the WHERE clause? Is that correct?

**Comment by ikwattro** [comment]
There is no issue with that kind of queries with parameters, make sure the value is an integer.

**Comment by nicolaschaillan** [comment]
You're right. Perhaps we can add this to the documentation I didn't realize integers in strings were automatically escaped. Sorry for the waste of your time
