### ISSUE TITLE
How to set timeout?

### ISSUE THREAD

**Issue by markharding** [graphaware/neo4j-php-client#16]
Is there a way to set the execution timeout? Currently a long cypher has now way to be halted if it takes too long from the client side. 

Thanks

**Comment by ikwattro** [comment]
Thanks for pointing this out. It has to come with a Configuration builder, but it is not totally ready yet. You can for now use the setDefaultTimeout method when building the connection, it is available now (alpha12) and documented here https://github.com/graphaware/neo4j-php-client#timeout .

Thanks !

**Comment by 0xfff** [comment]
the `setDefaultTimeout` feature has been deprecated, is there an example with httplug
im doing this, but getting `Recv failure: Connection reset by peer` exception:
```
$options = [
    CURLOPT_CONNECTTIMEOUT => 60, // The number of seconds to wait while trying to connect.
    CURLOPT_SSL_VERIFYPEER => false // Stop cURL from verifying the peer's certificate
];
use Http\Client\Curl\Client;
$httpClient = new Client(null, null, $options);

$config = \GraphAware\Neo4j\Client\HttpDriver\Configuration::create($httpClient);
use GraphAware\Neo4j\Client\ClientBuilder;
$neo4j  = ClientBuilder::create()
        -> addConnection('default', $neo_ip, $config)
        // -> setDefaultTimeout($neo_timeout)
        -> build();
```
