### ISSUE TITLE
Neoxygen\NeoClient\Client::sendCypherQuery - documentation mistake ?

### ISSUE THREAD

**Issue by ohaag** [graphaware/neo4j-php-client#18]
Hello,
in Neoxygen\NeoClient\Client l.30 we have:
`@method \Neoxygen\NeoClient\Formatter\Response sendCypherQuery(...`

However the sendCypherQuery method returns a Neoxygen\NeoClient\\**Request**\Response, even with auto_format_response set to true.

I'm just begining using this lib so I don't know if the problem is that the documentation is wrong or if the response SHOULD be a Formatter\Response.

In any case, if the response type depends of auto_format_response parameter, saying it returns a Formatter\Response is wrong. I'm not sure the `|` annotation is acceptable in order to do:
`@method \Neoxygen\NeoClient\Formatter\Response|\Neoxygen\NeoClient\Request\Response sendCypherQuery(...`

But the better way should be to do an interface if there really are many possible returned types.

**Comment by ikwattro** [comment]
Hi @ohaag 

If your're just beginning using this library, please use the 4.x version as stated in the README, the stable release will be tagged tomorrow after the announcement of neo4j 3.0.

The 3.x version is maintained for bug fixes only until Sep 16.

Thanks,

Let me know if you have problems upgrading to 4.x

**Comment by ohaag** [comment]
Thank you @ikwattro,
It comes timely for me :), I red neo4j-php-client 4.x support Neo4j >2.2.6 version so I can indeed migrate.
