### ISSUE TITLE
Should this fork be used over the original repository?

### ISSUE THREAD

**Issue by flip111** [graphaware/neo4j-php-client#2]
What's gonna be the main differences between this repo and it's original?

**Comment by ikwattro** [comment]
Currently, the original is still working and bug fixes are made there. The graphaware repository however will contain further updates and will integrate bolt (binary protocol in 3.0) in the future: 

https://github.com/graphaware/neo4j-bolt-php

So once the 4.0 branch is ready and stable, this repository will be the only one to use.

**Comment by ikwattro** [comment]
Also, this repository will be compliant with the upcoming Neo4j Technology Compliance Kit, meaning that GraphAware will support the driver for enterprise customers, which is beneficial for the opensource community too as there is a certitude of compatibility and recent upgrades

**Comment by flip111** [comment]
Maybe it's possible to change the readme's of this repo and/or the original repo to give more instruction about this?

**Comment by ikwattro** [comment]
This will be done, GraphAware having bought the intellectual property of the neoxygen components to me, there will be soon a blog post about it and the updated readmes will be following.

Nice you keep an eye of it. If you want to receive more informations about what will change or other informations about the neo4j world, just send me an email to christophe at graphaware dot com

**Comment by flip111** [comment]
thanks for the infos, the plans are looking good !
