### ISSUE TITLE
Would be nice if we could get stats about a tx or a stack...

### ISSUE THREAD

**Issue by frednotet** [graphaware/neo4j-php-client#21]
something like this : 
`$tx->commit()->summarize()->updateStatistics()`

because right now, it's an resultCollection and we have to iterate each results to get them...
;)

**Comment by ikwattro** [comment]
Added in 4.1.0

**Comment by 0xfff** [comment]
i would like the timing information that Neo returns, is that possible?

> Relationships created: 9074
> 488237 ms

`$relationships_created= $stats->relationshipsCreated();`

But what about the timing?

**Comment by ikwattro** [comment]
The Neo4j server doesn't return any timing as part of the Statistics informations, the timing you get in the neo browser is built using client side application code.

I agree though this would be a nice addition if the client would compute the timingd and make it available as part of the statistics.

This will ship in a new version begin of September.

Chris

**Comment by 0xfff** [comment]
Thank you.
I guess I can measure the timing in my script.
