### ISSUE TITLE
Wrong link in Readme.md

### ISSUE THREAD

**Issue by calpirro** [graphaware/neo4j-php-client#22]
Hi,

this link in _**Getting Help section**_ doesn't work...

```
Check out an example application built with GraphAware Neo4j Client
(https://github.com/neo4j-contrib/developer-resources/tree/gh-pages/language-guides/php/neoclient)
```

Thanks

**Comment by ikwattro** [comment]
Hi @calpirro , yes the Neo Technology developers pages are in refactoring right now. If you need help you can raise a github issue, open a question on StackOverflow by tagging your question with `graphaware` and `neo4j` or by asking your question in the neo4j-users slack. I'll update the README once I received the new link from the devrels at Neo.
