### ISSUE TITLE
query status like Neo4j Browser

### ISSUE THREAD

**Issue by darkeus** [graphaware/neo4j-php-client#3]
Does neo4j-php-client have a feature likes neo4j browser, so when i do an update cypher query, it will return a status how many label affected, propery set, or even how many removed node?

**Comment by ikwattro** [comment]
This is an upcoming feature in the 4.0 release.

**Comment by ikwattro** [comment]
@darkeus This has been implemented in https://github.com/graphaware/neo4j-php-client/commit/c49cb4c9f392637b9507b8ff12c24c404a72c013

Client v4.0 coming soon with all the updates

**Comment by ikwattro** [comment]
This is now implemented with `->summarize()->updateStatistics();`
