### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by 0xfff** [graphaware/neo4j-php-client#42]
```
composer require graphaware/neo4j-php-client
Using version ^4.4 for graphaware/neo4j-php-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: graphaware/neo4j-php-client[4.4.0, dev-master].
    - Can only install one of: graphaware/neo4j-php-client[4.4.1, dev-master].
    - Can only install one of: graphaware/neo4j-php-client[4.4.2, dev-master].
    - Can only install one of: graphaware/neo4j-php-client[4.4.3, dev-master].
    - Installation request for graphaware/neo4j-php-client dev-master -> satisfiable by graphaware/neo4j-php-client[dev-master].
    - Installation request for graphaware/neo4j-php-client ^4.4 -> satisfiable by graphaware/neo4j-php-client[4.4.0, 4.4.1, 4.4.2, 4.4.3].


Installation failed, reverting ./composer.json to its original content.
```

can someone point me in the right direction?

**Comment by 0xfff** [comment]
specifying dev-master solved the issue:
` composer require graphaware/neo4j-php-client dev-master`

**Comment by ikwattro** [comment]
@0xfff you shouldn't use dev-master. Can you give your current composer.json ?

**Comment by 0xfff** [comment]
```
{
    "name": "graphaware/neo4j-php-client",
    "type": "library",
    "description": "Neo4j-PHP-Client is the most advanced PHP Client for Neo4j",
    "keywords": [
        "graph",
        "database",
        "neo4j",
        "cluster",
        "client",
        "bolt",
        "http",
        "high-availibility"
    ],
    "homepage": "http://graphaware.com",
    "license": "MIT",
    "authors": [
        {
            "name": "Christophe Willemsen",
            "email": "christophe@graphaware.com"
        }
    ],
    "require": {
      "php": ">= 5.6",
      "graphaware/neo4j-bolt": "^1.5",
      "guzzlehttp/guzzle": "^6.0",
      "symfony/event-dispatcher": "^2.7|^3.0",
      "myclabs/php-enum": "^1.4",
        "graphaware/neo4j-php-client": "dev-master"
    },
    "require-dev": {
        "phpunit/phpunit": "4.*",
        "symfony/stopwatch": "^3.0"

    },
    "autoload": {
        "psr-4": {
            "GraphAware\\Neo4j\\Client\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "GraphAware\\Neo4j\\Client\\Tests\\": "tests/"
        }
    }
}

```

**Comment by ikwattro** [comment]
No this is the client's composer.json, I mean the one used by your application.

**Comment by 0xfff** [comment]
there isn't an application yet, just installed Neo4j the the neo4j-php-client

**Comment by ikwattro** [comment]
ok ok, so there shouldn't an issue. Make sure you have the following : 

* php 5.6+
* ext-mbstring
* ext-bcmath

**Comment by 0xfff** [comment]
php -m does list both bcmath & mbstring
running PHP 7.0.6-1

thank you for taking your time to address this btw.

**Comment by ikwattro** [comment]
No worries, the strange thing is that dev-master has the exact same requirements as 4.x

**Comment by 0xfff** [comment]
is there any downside to using dev-master?
this is on a development machine btw, when/if we move this to production we will do a clean install on a server

**Comment by ikwattro** [comment]
well dev-master can be a current unstable version with pending changes to be released in the next tagged version.

**Comment by notemood** [comment]
I have the same issue on a centos machine

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install graphaware/neo4j-php-client 4.4.3
    - Conclusion: don't install graphaware/neo4j-php-client 4.4.2
    - Conclusion: don't install graphaware/neo4j-php-client 4.4.1
    - Conclusion: remove graphaware/neo4j-bolt 1.4.2
    - Installation request for graphaware/neo4j-php-client ^4.4 -> satisfiable b
y graphaware/neo4j-php-client[4.4.0, 4.4.1, 4.4.2, 4.4.3].
    - Conclusion: don't install graphaware/neo4j-bolt 1.4.2
    - graphaware/neo4j-php-client 4.4.0 requires graphaware/neo4j-bolt ^1.5 -> s
atisfiable by graphaware/neo4j-bolt[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.
5.6, 1.5.7].
    - Can only install one of: graphaware/neo4j-bolt[1.5.0, 1.4.2].
    - Can only install one of: graphaware/neo4j-bolt[1.5.1, 1.4.2].
    - Can only install one of: graphaware/neo4j-bolt[1.5.2, 1.4.2].
    - Can only install one of: graphaware/neo4j-bolt[1.5.3, 1.4.2].
    - Can only install one of: graphaware/neo4j-bolt[1.5.4, 1.4.2].
    - Can only install one of: graphaware/neo4j-bolt[1.5.5, 1.4.2].
    - Can only install one of: graphaware/neo4j-bolt[1.5.6, 1.4.2].
    - Can only install one of: graphaware/neo4j-bolt[1.5.7, 1.4.2].
    - Installation request for graphaware/neo4j-bolt (locked at 1.4.2) -> satisf
iable by graphaware/neo4j-bolt[1.4.2].

**Comment by ikwattro** [comment]
@notemood Are you also just using `composer require graphaware/neo4j-php-client` ? If not, please share your composer.json.

Also can you paste the output of `php -m` 

Thanks !

**Comment by notemood** [comment]
I needed to include bolt manually in composer for it to work

```
    "graphaware/neo4j-bolt": "^1.5",
    "graphaware/neo4j-php-client": "^4.4",
```
It installed properly now!
