### ISSUE TITLE
value() and hasValue() methods

### ISSUE THREAD

**Issue by juliustm** [graphaware/neo4j-php-client#43]
I just updated my neo4j-php-client and i noticed something that can be improved.
Whenever **value()** method is called on a results object it throws an exception if the results object doesn't contain the specified value ( I know there is **hasValue()** method which can be used before calling **value()** method to prevent such exceptions ).

> Exception:this object has no property with key 'logo' 

Earlier neo4j-php-client versions were intelligent to check if the value exists first then return it or return null/empty if the value was not found. It becomes easier and it makes sense with how earlier versions worked compared to the current version which forces all **value()** calls to be proceeded with a call to **hasValue()** method so as to prevent exceptions when the value is not in the results object.

**Comment by ikwattro** [comment]
Hi,

Thanks for the feedback. Actually you can achieve what you want by passing a second argument to the value() method : 

```php
$logo = $record->get('n')->value('logo', null);
```

The same is valid for record identifiers : 

```php
$user = $record->get('user', null);
```

**Comment by juliustm** [comment]
Thank you, you just helped me save a couple of lines.
