### ISSUE TITLE
Database connections and management

### ISSUE THREAD

**Issue by squarefractal** [graphaware/neo4j-php-client#44]
This is not an issue; but rather a question on how database connections are handled by this client.
Specifically:

* Does this driver use a pool of connections and return client instances from that pool when `build()` is called?
* How should one go about closing connections (if this is required at all)?

**Comment by ikwattro** [comment]
Hey @squarefractal 

a) Nope, there is a pool of connections, not client instances. Actually this maybe should be called `databases` rather than connections, but I've left as it is for people being used to v3 before.

The goal is to point it to different databases, for example one master and 2 slaves, where you can choose to which database to send queries.

This is also helpful for migrations.

b) No need to close, it is done by the underlying driver.

**Comment by squarefractal** [comment]
Thank you for answering @ikwattro !

**Comment by squarefractal** [comment]
There's a related question I wanted to ask:

Since the driver connects over a network, is it fine to do something like this from a performance and software engineering POV?

	class Database {
		public static function getConnection() {
			return ClientBuilder::create()->addConnection('default', 'http://neo4j:password@localhost:7474')->build();
		}
	}

And then use it as:

    $db = Database::getConnection();

Or should I do something along the lines of, say:

	class Database {
		private static $connection = null;
		public static function getConnection() {
			if (!self::$connection === null) {
				self::$conn = ClientBuilder::create()->addConnection('default', 'http://neo4j:password@localhost:7474')->build();
			}
			return self::$conn;
		}
	}

**Comment by ikwattro** [comment]
The first option will create a new client for each connection, not optimal.

For the second, I don't see exactly why you want static clients ?

To me the best option is to use a dependency injection container and inject the client in the constructor of the classes where you need it.

**Comment by squarefractal** [comment]
The second variant just helps avoid the issue of creating new connections by creating one client instance and providing that to all callers. It is an ugly way to do it, though.

My actual question was actually: is there no way to be able to reuse the same client instance for use by multiple callers? And if it is indeed so, how should one go about optimizing the code so that it's not slowed down trying to create new client instances?

(And even if I use DI, it won't make much of a difference; as far as I can tell you will be handing out new Client instances to each object, which makes it equivalent to the first snippet. Or if you want to reuse the same Client instance, you'll be doing something similar to what the second snippet does. Of course the code is cleaner if I use DI, but that's another topic...)

**Comment by ikwattro** [comment]
No using DI is totally difference, you create a Singleton which is shared by all instances.

In a simplified version this would actually be what the code would look like using [Pimple](https://github.com/silexphp/Pimple) for example : 

```php
<?php
use Pimple\Container;
$container = new Container();

$container['neo4j'] = function ($c) {
  return ClientBuilder::create()->addConnection('default','bolt://localhost')->build();
}

$container['caller1'] = function ($c) {
  return new App\CallerA($c['neo4j']);
}

$container['caller2'] = function ($c) {
  return new App\CallerB($c['neo4j']);
}
```

By default, `$c['neo4j']` will return always the same instance of the Client.

**Comment by ikwattro** [comment]
On a side note, your option B is very similar to Laravel's facades by the way, people like it others don't, it is a matter of taste. I prefer to have explicit constructor injection rather than calling facades statically.

**Comment by squarefractal** [comment]
Thank you for your detailed explanation.
