### ISSUE TITLE
Strict requirement on PHP >= 5.6

### ISSUE THREAD

**Issue by sgehrig** [graphaware/neo4j-php-client#47]
Why is there a strict requirement on PHP >= 5.6? I quickly scanned the code and could not find any trace of any of the PHP 5.6-only features being used,

I know that PHP 5.5 is going to reach end of life shortly, but unfortunately it's still a given fact we have to deal with as our code is still being run on Ubuntu 14.04 for example. 

If there isn't a strict dependency on PHP >= 5.6 could this be changed to PHP >= 5.5?

**Comment by ikwattro** [comment]
@sgehrig There is a dependency on guzzle (which require php5.6). The second is the dependency on the Bolt Driver, there is a dependency on the Bolt driver (https://github.com/graphaware/neo4j-bolt-driver) which uses a binary protocol and rely heavily on the `pack()` and `unpack()` php functions. Those functions have additions in 5.6.3 which are needed to deal with 64 bits integers, like 

```
5.6.3	The "q", "Q", "J" and "P" codes were added to enable working with 64-bit numbers.
```

I tried to remove and find hacks or workaround, unfortunately it didn't go well or I ended with code that I didn't really want to maintain myself.

We also have clients on 5.5 but fortunately our use cases permit us to extract the neo4j logic into is own service and thus use a dedicated machine with a recent php version.

I hope it answers your question.

**Comment by sgehrig** [comment]
@ikwattro Thanks for the quick response. Guzzle seems to be >= 5.5 as well, but I see the problem with `pack` and `unpack`. That's why https://github.com/graphaware/neo4j-bolt-php/issues/10 is obsolete as well then.

Perhaps the Bolt driver could be an optional dependency on the client, but for now that's OK for me.

**Comment by ikwattro** [comment]
@sgehrig Ha 5.5 you're right. Yes I thought about moving it as optional dependency, I can leave the issue open but to be honest and so you know, this will not be in my priorities right now.

**Comment by sgehrig** [comment]
You're absolutely right. Given the fact that PHP 5.5 is a very temporary thing now, I don't see any priority here as well. If I do find some free time, I'll check whether extracting the Bolt driver into an optional dependency might be feasible.

**Comment by ikwattro** [comment]
Closing this issue as `will not fix`.
