### ISSUE TITLE
better exceptions from Neo

### ISSUE THREAD

**Issue by ikwattro** [graphaware/neo4j-php-client#5]
Ported from https://github.com/neoxygen/neo4j-neoclient/issues/70

reported by @flip111

**Comment by ikwattro** [comment]
Hi @flip111

In https://github.com/graphaware/neo4j-php-client/commit/726a1166e2b5b304180615fbdf7a55cc29d76064 You'll get the Neo4j status code iaw http://neo4j.com/docs/stable/status-codes.html

Also, there is a method `effect()` on the exception, which returns whether or not the transaction has been rolled back.

Keep up, the 4.0 release is coming in the next weeks

**Comment by flip111** [comment]
thank you @ikwattro

**Comment by ikwattro** [comment]
We see the end :)
