### ISSUE TITLE
Inconsistent behaviour of getRecord() over Bolt and HTTP when returning no records

### ISSUE THREAD

**Issue by squarefractal** [graphaware/neo4j-php-client#54]
When the Bolt protocol is used for connections, running a query that returns no records, and then trying to fetch them with `getRecord()` has a differing behaviour as compared to when HTTP is used.

When Bolt is used, an `InvalidArgumentException` is thrown:

	>>> $db = ClientBuilder::create()->addConnection('bolt', 'bolt://'.$username.':'.$password.'@localhost:7687')->build()
	=> GraphAware\Neo4j\Client\Client {#175}
	>>> $rv = $db->run('MATCH (x:NonExistentLabel) RETURN x')
	=> GraphAware\Bolt\Result\Result {#194}
	>>> $rv->getRecords()
	=> []
	>>> $rv->getRecord()
	InvalidArgumentException with message 'No records'

When HTTP is used, `getRecord()` returns `null`:

	>>> $db = ClientBuilder::create()->addConnection('default', 'http://'.$username.':'.$password.'@localhost:7474')->build()
	=> GraphAware\Neo4j\Client\Client {#175}
	>>> $rv = $db->run('MATCH (x:NonExistentLabel) RETURN x')
	=> GraphAware\Neo4j\Client\Formatter\Result {#212}
	>>> $rv->getRecords()
	=> []
	>>> $rv->getRecord()
	=> null

**Comment by ikwattro** [comment]
Thanks for the report, I'll make the fix.

Sorry for delay, was on holidays.

**Comment by ikwattro** [comment]
Fixed partially. Http throws RuntimeException, will modify bolt to do the same.

**Comment by squarefractal** [comment]
Wouldn't fixing Bolt behaviour to return null instead of an exception be the actual desired behaviour? Throwing an exception seems very counter-intuitive; and most database drivers return an empty result set (empty array/null/false/...) instead of throwing an exception when running queries that do not generate any results.

**Comment by ikwattro** [comment]
I agree this is not very friendly, unfortunately this is the specification of the Neo4j Drivers Technology Compliance Kit and I have to follow it in order to keep the driver "official".
