### ISSUE TITLE
cURL timeout

### ISSUE THREAD

**Issue by in3rsha** [graphaware/neo4j-php-client#56]
Hi there,

When trying to execute a large Cypher query, I'm getting a cURL timeout error.

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/user/project/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
```

Is there an easy way to increase the timeout time (or remove it completely) within the same script? Or should I be looking to update a file from one of the included composer libraries?

**Comment by 0xfff** [comment]
you can set it to whatever value you want
```
$neo4j = ClientBuilder::create()
->setDefaultTimeout(30000)
```

**Comment by 0xfff** [comment]
documentation here: https://github.com/graphaware/neo4j-php-client#timeout

**Comment by in3rsha** [comment]
Perfect, thank you for the quick help.

**Comment by 0xfff** [comment]
setDefaultTimeout has been deprecated, what is the new way of setting timeout?

**Comment by ikwattro** [comment]
@0xfff There is some documentation about how to do that with http-plug : 

https://github.com/graphaware/neo4j-php-client#http-client-settings

Note that, the chances are high that http will be dropped in version 5 (or deprecated and removed in v6). Decision will be made June 30 after the drivers author meeting with Neo.

**Comment by 0xfff** [comment]
related to #16, related to #88 
i am using that documentation but still cannot receive data from Neo4j (see #16 )
