### ISSUE TITLE
FirstRecord when no records

### ISSUE THREAD

**Issue by tomswinkels** [graphaware/neo4j-php-client#62]
Hi,

When i check if there is are first record like "if($result->firstRecord())" i get the error "RuntimeException in Result.php line 71: There is no recrods". (lol 'recrods' i think the error message are incorrect)

This works;
`if( $result->records() )
{
$record = $result->firstRecord();
}`

But i think that this is not the right way.

**Comment by ikwattro** [comment]
I agree this is not very friendly, unfortunately this is the specification of the Neo4j Drivers Technology Compliance Kit and I have to follow it in order to keep the driver "official".

In the meantime you can do the check like this for eg : 

```php
if ( 0 < $result->size() ) {
 // ...
}
```

Or you can just iterate the result records : 

```php
foreach ($result->records() as $record) {
 // ...
}
```

**Comment by ikwattro** [comment]
@tomswinkels I added a new method, where you can pass a default value, like this : 

```php
$firstRecord = $result->firstRecordOrDefault(null);

if (null !== $firstRecord) {
  //....
}
```

Note that there is still an `if` to perform in your code, so I don't know how much value such method can offer actually.

**Comment by tomswinkels** [comment]
Yeah, thankyou! :)

**Comment by xavismeh** [comment]
Great addition! However, don't you think it would make sense to provide a default value in method signature: `public function firstRecordOrDefault($default = null);` ?

**Comment by ikwattro** [comment]
Well, if you use this method it is an explicit intent, I would have understand that if the default parameter would have been set in firstRecord itself. The method name is also explicit on the subject.

However, I am happy to change my mind if other people agree with you, it is an oss project in that sense ;) 

Still travelling back from SFO thought, expect reactions tomorrow from me.
