### ISSUE TITLE
http works fine, but bolt connections fail

### ISSUE THREAD

**Issue by gordyr** [graphaware/neo4j-php-client#64]
I can connect and run queries fine when using an ```http``` connection:

```
   $client = ClientBuilder::create()
            ->addConnection('default', 'http://' . $this->_GRAPH_USERNAME . ':' . $this->_GRAPH_PASSWORD . '@' . $this->_GRAPH_ENDPOINT . ':' . $this->_GRAPH_HTTP_PORT)
            ->addConnection('bolt', 'bolt://' . $this->_GRAPH_USERNAME . ':' . $this->_GRAPH_PASSWORD . '@' . $this->_GRAPH_ENDPOINT . ':' . $this->_GRAPH_BOLT_PORT)
            ->build();
```

But the second I comment out the ```http``` connection and try to run a basic query such as:

```
$client->run("MATCH (n:Person) RETURN n");
```

Everything appears to fail silently.

Are there any common causes for this that I should be aware of?  Or Is there anyway I can catch any exceptions here to try and work out what's going on?

**Comment by ikwattro** [comment]
Is neo4j running with default ports ? If yes, what if you leave the port off in the url ?

**Comment by gordyr** [comment]
No, I am using [GrapheneDB](http://www.graphenedb.com/) which provides me with ports for both the ```http``` and the ```bolt``` connections.

I am querying from an Amazon EC2 instance which is correctly set up to allow inbound/outgoing traffic on the bolt port.

**Comment by ikwattro** [comment]
Allright, GrapheneDB uses TLS connections, you need to configure that like this : 

```php
$config = \GraphAware\Bolt\Configuration::newInstance()
    ->withCredentials('user', 'password'')
    ->withTLSMode(\GraphAware\Bolt\Configuration::TLSMODE_REQUIRED);

 $client = ClientBuilder::create()
            ->addConnection('default', 'http://' . $this->_GRAPH_USERNAME . ':' . $this->_GRAPH_PASSWORD . '@' . $this->_GRAPH_ENDPOINT . ':' . $this->_GRAPH_HTTP_PORT)
            ->addConnection('bolt', 'bolt://' . $this->_GRAPH_USERNAME . ':' . $this->_GRAPH_PASSWORD . '@' . $this->_GRAPH_ENDPOINT . ':' . $this->_GRAPH_BOLT_PORT, $config)
            ->build();

```

**Comment by gordyr** [comment]
Brilliant!  Thanks for the simple and concise answer!
