### ISSUE TITLE
Unable to retrieve node's properties

### ISSUE THREAD

**Issue by trishantofficial** [graphaware/neo4j-php-client#65]
Greetings!

While working on a little project using neo4j I required a wrapper to communicate with the database in php, and I cam across this one. So, on fiddling a little with the wrapper to learn it a bit first, I was facing a little problem. In ** \GraphAware\Neo4j\Client\Formatter\Type\Node** I was able to retrieve the node's labels using the provided method *italic* labels() but was unable to access the properties variable of the node class.

I found a solution to it too. We can add up a public function to return the *properties* variable, similar to the labels function. Might be useful! :nerd_face: 

![code](https://cloud.githubusercontent.com/assets/15844175/19656334/28cb6b7c-9a3d-11e6-8018-d26b9ebf06d7.png)

**Comment by ikwattro** [comment]
The `Node` class extends the `MapAccess` class which is the properties holder for nodes as well as relationships.

You can call the `values()` method on a `Node` or `Relationship` instance, you can find the api here : https://github.com/graphaware/neo4j-php-client/blob/master/src/Formatter/Type/MapAccess.php#L61

This method should appear though in phpstorm.
