### ISSUE TITLE
Support for Spatial plugin

### ISSUE THREAD

**Issue by Nyholm** [graphaware/neo4j-php-client#67]
I've been searching the web and I have not found anything about using the Spatial plugin with PHP. 

Is this supported by this client? On the TODO list? Or is there any workaround?

**Comment by ikwattro** [comment]
Simple answer: no

Long answer: Being a neo4j user for quite a long time now, I know the state of the spatial plugin and the vision of spatial at neo itself after speaking with Craig Taverner (author of spatial and working at neo). They don't have a lot of time to allocate to the neo4j spatial plugin and the vision is to move the spatial functions to neo4j itself (like it was done already with the point and distance functions available in 3.0 from Cypher). So providing support for spatial here (while this lib is actually really just a driver) would be a waste of time. Sorry.

**Comment by Nyholm** [comment]
Thank you for the answer. I was many things I did not know here. 

👍
