### ISSUE TITLE
How to create an id() param?

### ISSUE THREAD

**Issue by rudiedirkx** [graphaware/neo4j-php-client#68]
Parameters/arguments are perfect for `WHERE name = {name}` and `SET u += {data}`, but I can't seem to `WHERE id(u) = {id}`, because the server doesn't see it as an int, and it really wants a real int:

> Expected a numeric value for empty iterator, but got: 30

How do I use it as a real int argument?

For now, I do `sprintf('id(u) = %d', $id)`, but that seems silly for a library like this.

**Comment by rudiedirkx** [comment]
If I cast it to a real int in PHP before, it does work. Does the library handle that or does Neo4j? I wouldn't want string comparison to be handled like an int simply because it's a real int in PHP...

**Comment by rudiedirkx** [comment]
Oh wow, I see now that `30` and `'30'` are really different in Neo4j... Both direction comparison needs an exact match, so `30` never equals `'30'`. That's weird. Do I, the client, always have to cast all arguments to the correct type, so `age = 30` and `housenumber = '30'` ?

This is becoming more of a Neo4j question. Sorry.

**Comment by ikwattro** [comment]
This library doesn't do any casting, it is really just a driver. If neo4j is expecting an int (actually ids are `long` but php doesn't) then you pass an integer, that's it.
