### ISSUE TITLE
Declaration of Session must be compatible with SessionInterface

### ISSUE THREAD

**Issue by SolomonPowell** [graphaware/neo4j-php-client#75]
Hello,

When I attempt to send a Cypher Query, I get the following error:

`Fatal error: Declaration of GraphAware\Neo4j\Client\HttpDriver\Session::run($statement, $parameters = Array, $tag = NULL) must be compatible with GraphAware\Common\Driver\SessionInterface::run($statement, array $parameters = Array, $tag = NULL) in C:\path\to\file\vendor\graphaware\neo4j-php-client\src\HttpDriver\Session.php on line 23`

Any idea what's wrong?

Thanks!

**Comment by ikwattro** [comment]
it seems like you have a problem of versions of the client + commons, can you check the both versions and report here

**Comment by SolomonPowell** [comment]
I used the instructions in the Introduction to add the library to my dependencies, and the `neo4j-php-client` in require is listed at `"^4.0"` in my composer. 

The composer within neo4j-php-client has `neo4j-common` as `"^2.0"`.

I don't know if this is how you meant to check?

**Comment by 4k1r0** [comment]
I just had this error and in fact there was no "^" before version number in my composer.json.
I somehow did something wrong copypasting the composer install instruction.
Hop it might help

**Comment by ikwattro** [comment]
Thanks @4k1r0 for writing here
