### ISSUE TITLE
Re-introduce ping method.

### ISSUE THREAD

**Issue by in3rsha** [graphaware/neo4j-php-client#76]
I think it would be useful to re-introduce a ping method.

For example:

`$client = ClientBuilder::create()->addConnection('default', "http://user:pass@$localhost:7474")->build();`

`$client->ping();`

This way you could check if the client has a successful connection to the Neo4j server.

**Comment by ikwattro** [comment]
As the future will focus mainly on bolt and this is handled natively there, closing this issue as no-fix
