### ISSUE TITLE
$record->value(<name>) returning null

### ISSUE THREAD

**Issue by fillobotto** [graphaware/neo4j-php-client#77]
I'm retrieving a record from Neoj4 database is this way:

```
$result = $client->run("");
$record = $result->getRecord();
print_r($record->values());
````

Print output is the following:

> Array ( [0] => GraphAware\Neo4j\Client\Formatter\Type\Node Object ( [id:protected] => 10 [labels:protected] => Array ( [0] => User ) [properties:protected] => Array ( [Email] => email@hotmail.it [Banned] => 1 [Username] => myusername [DeviceID] =>  [Password] => mypass [Name] => myname) ) ) 

However I can't get node attribute:
`echo $record->value('Name');`

PHP prints this notice and return null value:

> Notice: Undefined index: Name in /var/www/html/wishit/vendor/graphaware/neo4j-php-client/src/Formatter/RecordView.php on line 73

**Comment by Nyholm** [comment]
How did you solve your issue?

**Comment by fillobotto** [comment]
The problem was that my query ended with

> RETURN n

So you needed to retrieve node element by doing

> $name = $record->get("n")->value("Name")

I didn't get this subtle difference by reading the docs once.

**Comment by koffisani** [comment]
Thanks, @fillobotto. You saved me.
