### ISSUE TITLE
Graphaware http connection issue

### ISSUE THREAD

**Issue by 3c4ng1s** [graphaware/neo4j-php-client#79]
So, this is the think I have downloaded Neo4j community edition to a cloud server running ubuntu server 15.10, not problem still there and have downloaded, installed, run and configure for remote access successfully Neo4j, so no problem still. I think that I downloaded well graphaware, since the folders and files all have been created, but when I introduce this code

`<?php

    require_once 'vendor/autoload.php';

    use GraphAware\Neo4j\Client\ClientBuilder;

    $client = ClientBuilder::create()
    ->addConnection('default', 'http://neo4j:password@localhost:7474')
    ->addConnection('bolt', 'bolt://neo4j:password@localhost:7687') 
    ->build();`

Is when everything go to wrongs, not only the connection is not created but it turn to an error where the website is not loaded and not even the error is show, so I suspect that is a problem with my graphaware installation or configuration. I have obviously changed password to my real password, try copying the hole vendor folder to my "public HTML" folder, deleting that copy, replacing localhost with my server ip, everything. Until now the most close that I have reach to find the problem's source it's that when I quote just the client builder, leaving the code like this:

`  <?php

    require_once 'vendor/autoload.php';

    use GraphAware\Neo4j\Client\ClientBuilder;
    /*
    $client = ClientBuilder::create()
    ->addConnection('default', 'http://neo4j:password@localhost:7474')
    ->addConnection('bolt', 'bolt://neo4j:password@localhost:7687') 
    ->build();
    */`

Then everything work, except for the fact that I'm not connected to the Neo4J

Don't get where I'm making the mistake, any help please??

**Comment by ikwattro** [comment]
Are there any logs on the server, exceptions, etc ?? I cannot really help with so little information I'm afraid

**Comment by 3c4ng1s** [comment]
I wouldn't truly know, I'm kind of noob new on Ubuntu Server and don't know how to search and look for any log or exceptions, if you could just tell me a command or a file where to find it I can provide that in search... as in internet I haven't found much on this topic either

**Comment by 3c4ng1s** [comment]
Haven't found any log or exception that could take to the mistake, all that I get is that the error is founded when the connection is try to be build, don't know if is could have to do with the fact that I have a MySQL connection already in place

**Comment by 3c4ng1s** [comment]
Hi, I don't know if this helps to help me but actually no log information is registered when enter the website

**Comment by 3c4ng1s** [comment]
Don't know how, but installing and reinstalling the json file and somehow it started working, just with a "plug it out, plug it and restart" and worked, but now when I upload a code with a function that would call a query, everything go to hell, the code is like this

`function register_user($username){
$client->run("CREATE (n:user) SET n += {infos}", ['infos' => ['user' => '$username']]);)");
}`

Now this is in another script file and both, the script file where I manage my connections and the file that run the query are requiere in the same, being the connection's one required before the one that handle the function. It shouldn't be a problem, is anything wrong with the code itselfor the file handling??
