### ISSUE TITLE
Remove dependency on Guzzle

### ISSUE THREAD

**Issue by Nyholm** [graphaware/neo4j-php-client#84]
We should not be dependent on an concrete implementation like Guzzle. It means that people stuck with Guzzle5 cannot use this excellent library. 

I suggest to use [HTTPlug](http://docs.php-http.org/en/latest/index.html) instead. It is an abstraction over HTTP clients so the end user can decide and configure the client themselves. 

Disclaimer: I am a co-creator of HTTPlug.

**Comment by ikwattro** [comment]
Yup, this makes sense!

**Comment by Nyholm** [comment]
Do you want me to submit a PR?

**Comment by Nyholm** [comment]
Im happy to do the work if you want me to

**Comment by ikwattro** [comment]
Hey @Nyholm Feel free to do so. I see of course no objection but I definitely live with it as it is now. Up to you ;-)
