### ISSUE TITLE
pthreads & neo4j-php-client

### ISSUE THREAD

**Issue by 0xfff** [graphaware/neo4j-php-client#91]
In order to perform some work in the given timeframe i need to use a multi-threaded approach.
I am having issues with executing neo4j queries, any call to `->run` yield a segfault

This is the run function from my thread class
```
public function run() {
        $id = $this->thread_id;
        $addr_array = $this->addr_array;
        $neo_ip = $this->neo_ip;
        $neo_timeout = $this->neo_timeout;
        $neo4j  = ClientBuilder::create()
        -> addConnection('default', $neo_ip)
        -> setDefaultTimeout($neo_timeout)
        -> build();

        $query = "MATCH a...."
            try{
                $result = $neo4j->run ($query);
                } 
            catch (Exception $e) {
            }
}
```
i get a segfault here: `$result = $neo4j->run ($query);`

any pointers would be appreciated.

**Comment by ikwattro** [comment]
I'm afraid I cannot help without more details. Also I think that if you want to do multi-thread you are using the wrong language.

**Comment by 0xfff** [comment]
Unfortunately at this time i am limited to PHP.
What details would shine more light on this?

**Comment by ikwattro** [comment]
You can use xdebug to diagnose the segfault. I understand the limitation however I think usage a message queue like rabbitmq would solve your needs in 99.99% of the use cases and avoid you a lot of headaches of trying multi-threading (speaking from my experience of course)
