### ISSUE TITLE
Result iteration with "twig"

### ISSUE THREAD

**Issue by sfdreverman** [graphaware/neo4j-php-client#93]
When using my query result in Twig (within symfony), I cannot seem to get hold of the "properties" of the returned records. Nodes within that result set are 'unknown', so they give an exception when you want to access them. However, when the result is dumped ( {{ dump(result) }} the properties and its contents are shown.

Is there a way to make the result set openly navigable by twig?

**Comment by Nyholm** [comment]
Can you show some code that are failing?

**Comment by ikwattro** [comment]
I don't have any issue with Twig : 

```php
public function indexAction()
    {
        $records = $this->getProducts();

        return array('records' => $records);
    }


    private function getProducts()
    {
        $client = ClientBuilder::create()
            ->addConnection('default', 'http://localhost:7474')
            ->build();

        $result = $client->run('MATCH (n:Product) RETURN n LIMIT 10');

        return $result->records();
    }
```

```
{% extends 'MyBundle:Default:base.html.twig' %}

{% block content %}

    {% for record in records %}
        {% for prop in record.get('n').values() %}
            <p>{{ prop }}</p>
        {% endfor %}
    {% endfor %}

{% endblock %}
```

```
1486217958

633201

13fa3730-f831-11e6-a180-0a73b7c8b72d

1486224821

633354

13faac60-f831-11e6-a180-0a73b7c8b72d

1486225710

633370

13faac61-f831-11e6-a180-0a73b7c8b72d

1486241710
```

**Comment by sfdreverman** [comment]
Ah, you're passing only the 'records' to twig. I passed the whole lot. And did not use the 'get' method to get into the Node. Just tried to access "record.properties['Name']" for instance. (navigating what you see when you dump the info) That does give an error message.

**Comment by ikwattro** [comment]
Well you can the Result as well. Trying to do `record.properties['Name']` expect there would be a properties array accessible publicly which is not the case. Check what methods are accessible on the Result, Record or Node classes and just use them in Twig and you should be good to go.

**Comment by sfdreverman** [comment]
The properties is inaccessible indeed, so this solves it. Thanks!
